#!/usr/bin/env node
var argv = require('yargs')
        .default('env', 'prod') // Server-side hook
        .help('h')
        .alias('h', 'help')
        .epilog('Copyright 2015')
        .example(
            '$0 refs/heads/test f3d7c49c850f9ad7559d41432496556b53599e50 b7cf9aeb4ce372c497dd0fe6057c06739a9d5bd8',
            'update hook (stops specific refs on non-0 exit)'
        )
        .usage('Usage: $0 <Reference name> <old object name> <new object name>')
        .demand(3)
        .argv,
    readline = require('readline'),
    rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
    }),
    gitKeys = Object.keys(process.env).filter(function (key) {
        return (key.lastIndexOf('GIT_', 0) === 0);
    }),
    gitObject = {};

gitKeys.forEach(function (key) {
    gitObject[key] = process.env[key];
});
console.log('Args:', argv);
console.log('CWD:', process.cwd());
console.log('__dirname:', __dirname);
console.log(gitObject);

rl.on('line', function (cmd) {
    console.log('STIDIN: ' + cmd);
}).on('close', function () {
    process.exit(0);
});
